### ISSUE TITLE
Initial feedback

### ISSUE THREAD

**Issue by NateWr** [artze/group-project-jsf-grades#1]
This is great! I love the table output. I'll try to add that to the other projects. I don't have any substantive changes to suggest, just a couple small things here and there:

- [x] Can you move the `npm install` step into the First Steps section of the Readme? We'll ask them to go through these together as a group on the day so they're less likely to miss it there.
- [x] Let's rename the `gradesArr` variable to `classGrades` and move it down to just above the console logs. I want to reinforce the distinction between function args and the variables that are passed into them. 
- [x] Is the docblock keyword `@returns` or `@return`? I've always used `@return` but now I'm not sure. Just want to make sure we use the same across all projects.
- [x] What do you think about adding a task for `averagePassingGrade()`? Then we could encourage them to reuse `showOver50()` and `calculateAverage()`.

I'm happy to do any of this if you don't have the time. When you're ready, I'll move this over to the CodeYourFuture account. I'll try to finalise everything and get all the project repos matched up on Friday.

Thanks!

**Comment by artze** [comment]
I should be able to do them this week so no worries! 

As for jsdoc both `@returns` and `@return` are usable, see [here](http://usejsdoc.org/tags-returns.html). I'm using `@returns` out of habit :) I could switch to `@return` if that is what we're sticking to in CodeYourFuture. Let me know.

All other items sound good!
